name: build our image

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: |
          sudo apt update -y
          sudo apt install -y libsystemd-dev gcc-aarch64-linux-gnu
          make build-container
          docker inspect gcr.io/k8s-staging-npd/node-problem-detector:v1
#         run: make
